---
title: "Task `r params$task`"
output: html_document
params:
  task: "2024-01-09_gamma"
---

```{r, include = FALSE}
suppressWarnings(suppressMessages(library(knitr)))
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      results = FALSE)
suppressWarnings(suppressMessages(library(dplyr)))
suppressWarnings(suppressMessages(library(ggplot2)))
suppressWarnings(suppressMessages(library(stringr)))
suppressWarnings(suppressMessages(library(patchwork)))
```

```{r initial_settings}
task_path <- file.path("output",
                       params$task)

files <- list.files(path = task_path, full.names = TRUE) %>% stringr::str_subset("res.Rds") 

res <- Reduce(bind_rows, lapply(files, readRDS))
```

## Training data plots

```{r train_plots, results = TRUE}
for (row in seq_along(1:nrow(res))) {
  train_plot  <- res$train_plot[[row]] + labs(subtitle = res$file[[row]],
                                              caption = "Training data set")
  valid_plot <- res$valid_plot[[row]] + labs(subtitle = res$file[[row]],
                                             caption = "Validation data set")
  print(train_plot / valid_plot)
}
```

